# config.yml

backend:
  name: github
  repo: tgerke/distill-with-netflifyCMS
  branch: main
  site_domain: suspicious-banach-9942aa.netlify.app

media_folder: 'images/uploads'

collections:
  - name: 'edit_about'
    label: 'about'
    files:
      - {file: 'about.Rmd', label: "Title", name: "title", widget: "string"}
